apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: failed-pod-cleaner-
resources:
- service-account.yaml
- cluster-role.yaml
- role-binding.yaml
- deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app: failed-pod-cleaner
