apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cleaner-image
  newName: ghcr.io/yousysadmin/failed-pod-cleaner
  newTag: latest
namespace: default
resources:
- ./base

# Path ServiceAccount namespace for ClusterRoleBinding
replacements:
  - source:
      kind: ServiceAccount
      name: service-account
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterRoleBinding
          name: cluster-role-binding
        fieldPaths:
          - subjects.0.namespace